/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as ImportacoesIndexRouteImport } from './routes/importacoes.index'
import { Route as ImportacoesIdRouteImport } from './routes/importacoes.$id'
import { Route as ProgramacaoIndexRouteImport } from './routes/programacao.index'
import { Route as ProgramacaoImportarRouteImport } from './routes/programacao.importar'
import { Route as ProgramacaoRevisarRouteImport } from './routes/programacao.revisar'
import { Route as ImportacoesAuditoriaIdRouteImport } from './routes/importacoes.auditoria.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesIndexRoute = ImportacoesIndexRouteImport.update({
  id: '/importacoes/',
  path: '/importacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesIdRoute = ImportacoesIdRouteImport.update({
  id: '/importacoes/$id',
  path: '/importacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoIndexRoute = ProgramacaoIndexRouteImport.update({
  id: '/programacao/',
  path: '/programacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoImportarRoute = ProgramacaoImportarRouteImport.update({
  id: '/programacao/importar',
  path: '/programacao/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRevisarRoute = ProgramacaoRevisarRouteImport.update({
  id: '/programacao/revisar',
  path: '/programacao/revisar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesAuditoriaIdRoute = ImportacoesAuditoriaIdRouteImport.update({
  id: '/importacoes/auditoria/$id',
  path: '/importacoes/auditoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/rota': typeof RotaRoute
  '/importacoes/$id': typeof ImportacoesIdRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao/revisar': typeof ProgramacaoRevisarRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/programacao/': typeof ProgramacaoIndexRoute
  '/importacoes/auditoria/$id': typeof ImportacoesAuditoriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/rota': typeof RotaRoute
  '/importacoes/$id': typeof ImportacoesIdRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao/revisar': typeof ProgramacaoRevisarRoute
  '/importacoes': typeof ImportacoesIndexRoute
  '/programacao': typeof ProgramacaoIndexRoute
  '/importacoes/auditoria/$id': typeof ImportacoesAuditoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/rota': typeof RotaRoute
  '/importacoes/$id': typeof ImportacoesIdRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao/revisar': typeof ProgramacaoRevisarRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/programacao/': typeof ProgramacaoIndexRoute
  '/importacoes/auditoria/$id': typeof ImportacoesAuditoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/mapa'
    | '/rota'
    | '/importacoes/$id'
    | '/programacao/importar'
    | '/programacao/revisar'
    | '/importacoes/'
    | '/programacao/'
    | '/importacoes/auditoria/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/mapa'
    | '/rota'
    | '/importacoes/$id'
    | '/programacao/importar'
    | '/programacao/revisar'
    | '/importacoes'
    | '/programacao'
    | '/importacoes/auditoria/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/mapa'
    | '/rota'
    | '/importacoes/$id'
    | '/programacao/importar'
    | '/programacao/revisar'
    | '/importacoes/'
    | '/programacao/'
    | '/importacoes/auditoria/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  MapaRoute: typeof MapaRoute
  RotaRoute: typeof RotaRoute
  ImportacoesIdRoute: typeof ImportacoesIdRoute
  ProgramacaoImportarRoute: typeof ProgramacaoImportarRoute
  ProgramacaoRevisarRoute: typeof ProgramacaoRevisarRoute
  ImportacoesIndexRoute: typeof ImportacoesIndexRoute
  ProgramacaoIndexRoute: typeof ProgramacaoIndexRoute
  ImportacoesAuditoriaIdRoute: typeof ImportacoesAuditoriaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes/': {
      id: '/importacoes/'
      path: '/importacoes'
      fullPath: '/importacoes/'
      preLoaderRoute: typeof ImportacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes/$id': {
      id: '/importacoes/$id'
      path: '/importacoes/$id'
      fullPath: '/importacoes/$id'
      preLoaderRoute: typeof ImportacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao/': {
      id: '/programacao/'
      path: '/programacao'
      fullPath: '/programacao/'
      preLoaderRoute: typeof ProgramacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao/importar': {
      id: '/programacao/importar'
      path: '/programacao/importar'
      fullPath: '/programacao/importar'
      preLoaderRoute: typeof ProgramacaoImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao/revisar': {
      id: '/programacao/revisar'
      path: '/programacao/revisar'
      fullPath: '/programacao/revisar'
      preLoaderRoute: typeof ProgramacaoRevisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes/auditoria/$id': {
      id: '/importacoes/auditoria/$id'
      path: '/importacoes/auditoria/$id'
      fullPath: '/importacoes/auditoria/$id'
      preLoaderRoute: typeof ImportacoesAuditoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  MapaRoute: MapaRoute,
  RotaRoute: RotaRoute,
  ImportacoesIdRoute: ImportacoesIdRoute,
  ProgramacaoImportarRoute: ProgramacaoImportarRoute,
  ProgramacaoRevisarRoute: ProgramacaoRevisarRoute,
  ImportacoesIndexRoute: ImportacoesIndexRoute,
  ProgramacaoIndexRoute: ProgramacaoIndexRoute,
  ImportacoesAuditoriaIdRoute: ImportacoesAuditoriaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
