/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ProgramacaoIndexRouteImport } from './routes/programacao.index'
import { Route as ProgramacaoImportarRouteImport } from './routes/programacao.importar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoIndexRoute = ProgramacaoIndexRouteImport.update({
  id: '/programacao/',
  path: '/programacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoImportarRoute = ProgramacaoImportarRouteImport.update({
  id: '/programacao/importar',
  path: '/programacao/importar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao/': typeof ProgramacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao': typeof ProgramacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/mapa': typeof MapaRoute
  '/programacao/importar': typeof ProgramacaoImportarRoute
  '/programacao/': typeof ProgramacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/configuracoes' | '/mapa' | '/programacao/importar' | '/programacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/configuracoes' | '/mapa' | '/programacao/importar' | '/programacao'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/mapa'
    | '/programacao/importar'
    | '/programacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  MapaRoute: typeof MapaRoute
  ProgramacaoImportarRoute: typeof ProgramacaoImportarRoute
  ProgramacaoIndexRoute: typeof ProgramacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao/': {
      id: '/programacao/'
      path: '/programacao'
      fullPath: '/programacao/'
      preLoaderRoute: typeof ProgramacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao/importar': {
      id: '/programacao/importar'
      path: '/programacao/importar'
      fullPath: '/programacao/importar'
      preLoaderRoute: typeof ProgramacaoImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  MapaRoute: MapaRoute,
  ProgramacaoImportarRoute: ProgramacaoImportarRoute,
  ProgramacaoIndexRoute: ProgramacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
